name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

#      - name: Archive test-results
#        if: always()
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: Test-Results
#          path: core/build/reports/tests/allTests
